---
cache_dir: ~/tmp/battleschool

sources:
  git: 
    - name: 'linux-dev-battleschool'
      repo: 'https://github.com/periclesmacedo/ansible-dev-linux'
      playbooks:
        - git.yml
        - rvm.yml
        - chrome.yml
